name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      shell: bash
      run: |
        python -m pip install --upgrade setuptools wheel pip setuptools-scm
        pip install mojimoji pytest
    - name: Preprocess data
      run: |
        make all
        pip install .
    - name: Run tests
      run: |
        pytest
    - name: Publish to PyPI if tagged
      if: startsWith(github.ref, 'refs/tags') && matrix.python-version == 3.10
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install twine setuptools-scm build
        python -m build
        twine upload dist/posuto*.tar.gz

